### ISSUE TITLE
how to add more obstacle

### ISSUE THREAD

**Issue by zdx3578** [biaslab/MultiAgentTrajectoryPlanning#2]
thanks for your work ,  add more obstacke just in env add more rectange? need change other ?

<img width="398" alt="image" src="https://github.com/biaslab/MultiAgentTrajectoryPlanning/assets/382863/fc5a8d7d-792e-4a47-b315-bbd05e3e625b">

![jl_je7ED0t4Ng](https://github.com/biaslab/MultiAgentTrajectoryPlanning/assets/382863/5909544e-88cd-49ae-87bb-9449cb8c01ba)

**Comment by bartvanerp** [comment]
The plotting/animation is currently configured for just 2 obstacles: https://github.com/biaslab/MultiAgentTrajectoryPlanning/blob/8d5a8d55b1110f04d649acfa3f8017fc1a8edd30/door.jl#L328-L329
So if you use more obstacles, these might not appear on the figures, whereas they are taken into account during inference. Extension towards plotting more than two obstacles should be trivial.

With respect to the correctness of the simulation results, there are several factors influencing the resulting behavior. I can't judge what happens in the animation you share and some aspects are still under active research.

**Comment by zdx3578** [comment]
change code is like the git diff, so result like some wrong.

**Comment by bartvanerp** [comment]
I would not go as far as saying that the presented results are wrong. There are multiple factors affecting the results, such as the number of discretization steps, initialization of the algorithm, number of message passing iterations and hyperparameters settings. For the situation you show I expect the number of discretization steps in combination with the prior precision on the control to cause the agents to move through the walls. This is a result of decreasing the size of the agents and the width of the rectangles.

**Comment by zdx3578** [comment]
![jl_9yD2fCrOVM](https://github.com/biaslab/MultiAgentTrajectoryPlanning/assets/382863/61407f33-5e6f-478a-baed-17031b158490)

thanks your explain, i still confusion , expect more document;

**Comment by bartvanerp** [comment]
Unfortunately there will not be any documentation on this repository. The accompanying paper, once published, might help.
